/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenshotScannerRouteImport } from './routes/screenshot-scanner'
import { Route as ScamAnalyzerRouteImport } from './routes/scam-analyzer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurrencyDetectorRouteImport } from './routes/currency-detector'
import { Route as IndexRouteImport } from './routes/index'

const ScreenshotScannerRoute = ScreenshotScannerRouteImport.update({
  id: '/screenshot-scanner',
  path: '/screenshot-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamAnalyzerRoute = ScamAnalyzerRouteImport.update({
  id: '/scam-analyzer',
  path: '/scam-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyDetectorRoute = CurrencyDetectorRouteImport.update({
  id: '/currency-detector',
  path: '/currency-detector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/currency-detector': typeof CurrencyDetectorRoute
  '/dashboard': typeof DashboardRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
  '/screenshot-scanner': typeof ScreenshotScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/currency-detector': typeof CurrencyDetectorRoute
  '/dashboard': typeof DashboardRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
  '/screenshot-scanner': typeof ScreenshotScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/currency-detector': typeof CurrencyDetectorRoute
  '/dashboard': typeof DashboardRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
  '/screenshot-scanner': typeof ScreenshotScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/currency-detector'
    | '/dashboard'
    | '/scam-analyzer'
    | '/screenshot-scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/currency-detector'
    | '/dashboard'
    | '/scam-analyzer'
    | '/screenshot-scanner'
  id:
    | '__root__'
    | '/'
    | '/currency-detector'
    | '/dashboard'
    | '/scam-analyzer'
    | '/screenshot-scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrencyDetectorRoute: typeof CurrencyDetectorRoute
  DashboardRoute: typeof DashboardRoute
  ScamAnalyzerRoute: typeof ScamAnalyzerRoute
  ScreenshotScannerRoute: typeof ScreenshotScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screenshot-scanner': {
      id: '/screenshot-scanner'
      path: '/screenshot-scanner'
      fullPath: '/screenshot-scanner'
      preLoaderRoute: typeof ScreenshotScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-analyzer': {
      id: '/scam-analyzer'
      path: '/scam-analyzer'
      fullPath: '/scam-analyzer'
      preLoaderRoute: typeof ScamAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-detector': {
      id: '/currency-detector'
      path: '/currency-detector'
      fullPath: '/currency-detector'
      preLoaderRoute: typeof CurrencyDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrencyDetectorRoute: CurrencyDetectorRoute,
  DashboardRoute: DashboardRoute,
  ScamAnalyzerRoute: ScamAnalyzerRoute,
  ScreenshotScannerRoute: ScreenshotScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
