/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScamAnalyzerRouteImport } from './routes/scam-analyzer'
import { Route as IndexRouteImport } from './routes/index'

const ScamAnalyzerRoute = ScamAnalyzerRouteImport.update({
  id: '/scam-analyzer',
  path: '/scam-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scam-analyzer': typeof ScamAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scam-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scam-analyzer'
  id: '__root__' | '/' | '/scam-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScamAnalyzerRoute: typeof ScamAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scam-analyzer': {
      id: '/scam-analyzer'
      path: '/scam-analyzer'
      fullPath: '/scam-analyzer'
      preLoaderRoute: typeof ScamAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScamAnalyzerRoute: ScamAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
